---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Executa Tarefas Communs nos nós do Kubernetes
      include_tasks:
        common-tasks.yaml

    - meta: flush_handlers

    - name: Cria o diretório data
      file:
        path: /home/suporte/data
        state: directory
        owner: suporte
        group: suporte
        mode: '0755'
        
    - name: Criando o arquivo authorized_keys
      copy:
        src: files/authorized_keys
        dest: /home/suporte/.ssh/authorized_keys
        owner: suporte
        group: suporte
        mode: 0644

    - name: Copia o arquivo join-command.sh
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Adiciona o node no cluster
      command: sh /tmp/join-command.sh
  
  handlers:
    - name: restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
        
    - name: Reiniciar o servico sshd
      systemd:
        name: sshd
        state: restarted